updated JenkinsFile for as per pruduction ready

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -16,7 +16,9 @@ pipeline {
 
     stage('Build and Test') {
       steps {
-        sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
+        dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
+          sh 'mvn clean package'
+        }
       }
     }
 
@@ -25,8 +27,10 @@ pipeline {
         SONAR_URL = "http://34.229.151.88:9000"
       }
       steps {
-        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
-          sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
+        dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
+          withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
+            sh 'mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
+          }
         }
       }
     }
@@ -36,36 +40,51 @@ pipeline {
         DOCKER_IMAGE = "abhishekoffice/ultimate-cicd:${BUILD_NUMBER}"
       }
       steps {
-        script {
-            sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
+        dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
+          script {
+            sh "docker build -t ${DOCKER_IMAGE} ."
             def dockerImage = docker.image("${DOCKER_IMAGE}")
             docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
-                dockerImage.push()
+              dockerImage.push()
             }
+          }
         }
       }
     }
 
     stage('Update Deployment File') {
-        environment {
-            GIT_REPO_NAME = "END-to-END-project-jenkins-with-ArgoCD"
-            GIT_USER_NAME = "abhishekofficial552266"
+      environment {
+        GIT_REPO_NAME = "END-to-END-project-jenkins-with-ArgoCD"
+        GIT_USER_NAME = "abhishekofficial552266"
+      }
+      steps {
+        script {
+          withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
+
+            sh """
+              git config user.email "abhishekkarmakar229@gmail.com"
+              git config user.name "Abhishek Karmakar"
+
+              sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+
+              git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+
+              git commit -m "Update deployment image to version ${BUILD_NUMBER}" || echo "No changes to commit"
+
+              git push https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
+            """
+          }
         }
-        steps {
-            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                sh '''
-                    git config user.email "abhishekkarmakar229@gmail.com"
-                    git config user.name "Abhishek Karmakar"
+      }
+    }
+  }
 
-                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-
-                    git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                    git commit -m "Update deployment image to version ${BUILD_NUMBER}" || echo "No changes to commit"
-
-                    git push https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
-                '''
-            }
-        }
+  post {
+    success {
+      echo "Pipeline executed successfully 🚀"
+    }
+    failure {
+      echo "Pipeline failed ❌"
     }
   }
 }
